# Generated by Django 4.0.5 on 2025-01-04 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiculo',
            options={'permissions': [('visualizar_catalogo', 'Puede visualizar el catálogo de vehículos'), ('add_vehiculomodel', 'Puede agregar un vehículo')]},
        ),
    ]
